### ISSUE TITLE
Error: release-please failed: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by drstrangelooker** [googleapis/release-please-action#1049]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Is this a client library issue or a product issue? We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - Programming language: monorepo - TS, Python, Go, Kotlin, CSharp, Swift
  - OS: Ubuntu latest 
  - Language runtime version:
  - Package version: v4 tested with v4 and with v4.1.2 specifically

#### Steps to reproduce

  1. Run release-please-action in the [sdk-codegen repo](https://github.com/looker-open-source/sdk-codegen).
  2. Expect to update the existing PR, instead get `Error: release-please failed: Cannot read properties of undefined (reading 'replace')`.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by drstrangelooker** [comment]
Additional info from running with `--debug`

```
TypeError: Cannot read properties of undefined (reading 'replace')
    at safeBranchName (/usr/local/google/home/drstrangelove/release-please/node_modules/release-please/build/src/util/branch-name.js:214:23)
    at BranchName.ofGroupTargetBranch (/usr/local/google/home/drstrangelove/release-please/node_modules/release-please/build/src/util/branch-name.js:63:93)
    at LinkedVersions.run (/usr/local/google/home/drstrangelove/release-please/node_modules/release-please/build/src/plugins/linked-versions.js:128:58)
    at Manifest.buildPullRequests (/usr/local/google/home/drstrangelove/release-please/node_modules/release-please/build/src/manifest.js:405:51)
    at async Object.handler (/usr/local/google/home/drstrangelove/release-please/node_modules/release-please/build/src/bin/release-please.js:328:34)
```
