### ISSUE TITLE
Was this repository recently moved?

### ISSUE THREAD

**Issue by ellisio** [googleapis/release-please-action#980]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do: Run releases using `google-github-actions/release-please-action`.
- What code you've already tried: What we've been running.
- Any error messages you're getting: This repo is now under `googleapis/release-please-action`. GitHub Actions _does not_ follow redirects when resolving a `uses` action. This has broken quite a bit of our deployment pipeline for many repos and orgs we've setup. Next time, we'll fork just to be safe, but if this was recently moved I'm not sure if you folks are aware of how this breaks GHA workflows.

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Comment by john-schroeder-volusion** [comment]
For reference, the error message we are seeing in our github action log is: `Error: Unable to resolve action. Repository not found: google-github-actions/release-please-action`

I imagine many people will be searching for it shortly.

**Comment by ellisio** [comment]
If ya'll want us to follow a "no release on Friday thing"... You could just ask.

**Comment by kphatak** [comment]
🍻

**Comment by kphatak** [comment]
Literally broke a bunch of our automations!

**Comment by VeronicaMV** [comment]
Could we please have the readme updated as well?

**Comment by simon-connektica** [comment]
That's it, I'm done. I'm switching to Bing.

**Comment by zepeng811** [comment]
Can the maintainer clarify if this is an intended change and we can start updating the repo owner accordingly? (And the README for this repository should be updated)

the worst case is we updated all our workflows and found out that the repo got moved back to the old owner `google-github-actions`

**Comment by agrahamlincoln** [comment]
I'm in the same position of @zepeng811 - I will gladly create a custom composite action that wraps this one to make it easier to manage this in the future, but I don't want to make any changes without knowing whether this will be reverted. This change clearly is causing widespread disruption so I'm hoping for some immediate guidance before I take action

**Comment by sebmellen** [comment]
Nice work breaking all of our release workflows on a Friday afternoon! Really love knowing that we can rely on Google to be a stable partner :)

**Comment by derekwinters** [comment]
FWIW, this will break [release-please](https://github.com/googleapis/release-please/blob/cb106cd0b5ae5c3e2a3b015487dc615eba72b842/.github/workflows/ci.yaml#L66) too. So at least the impact of this change will be felt internally too 😆

**Comment by gustavo-cycling** [comment]
Well done. If you actually did your job instead of spending the whole day posting garbage on memegen mocking other companies maybe, just maybe, things like this would not happen. Can't fault that Pinchas guy for laying of so many of you.

**Comment by SialB** [comment]
Hi there, you can fix this change by using the new location btw `uses: googleapis/release-please-action@v4` in your GitHub actions!

**Comment by DuncanCasteleyn** [comment]
Due to the move this action is no longer a verified action.

\[Error\] googleapis/release-please-action is not allowed to be used in arg-credit/workflows. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, verified in the GitHub Marketplace, or matching the following: *redacted*.

**Comment by peterhirn** [comment]
fyi pinned actions seem to still work without issues (future renovate updates probably broken)

```yaml
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@a37ac6e4f6449ce8b3f7607e4d97d0146028dc0b # v4
```

**Comment by arunpgmi** [comment]
For reference, the error message we are seeing in our github action log is: Error: Unable to resolve action. Repository not found: google-github-actions/release-please-action . Request you to fix the same

====================
##[debug]GitHub.DistributedTask.WebApi.UnresolvableActionDownloadInfoException: Unable to resolve action. Repository not found: google-github-actions/release-please-action
##[debug]   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
##[debug]   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)

**Comment by mkniewallner** [comment]
It's a bit sad that GitHub Actions do not follow renamings like it does when cloning a repository, to not break old references. It may be on purpose, but since it might not be the case, I've opened a discussion about that: https://github.com/orgs/community/discussions/123611.

**Comment by chgryan** [comment]
also getting this. any word?

**Comment by jfklingler** [comment]
Excellent demonstration of commit-and-run on a Friday afternoon. 👏  Can someone from Google please let us know for certain whether this was an oops and will be reverted or if this is indeed `release-please-action`'s new forever home (for some definition of forever)?

**Comment by chingor13** [comment]
We sincerely apologize for the disruption caused by the repository move. We understand this has impacted your workflows and we deeply regret the inconvenience this has caused.

The decision to move the repository was driven by internal organizational policies. We mistakenly assumed that GitHub's redirection mechanism, which typically works seamlessly for the UI and git operations, would also apply to actions. This was clearly an oversight on our part.

We are working to restore a copy of the repository to the `google-github-actions` organization as quickly as possible. However, please note that all future development will occur in the `googleapis` organization.

**Comment by ramonsnir** [comment]
@chingor13 Note that the organization and the GitHub action lost their "verified" status on GitHub. This is an issue for some supply chain security tools, which use this as one layer out of many.

**Comment by DuncanCasteleyn** [comment]
> @chingor13 Note that the organization and the GitHub action lost their "verified" status on GitHub. This is an issue for some supply chain security tools, which use this as one layer out of many.

I have created an issue to track the progress of the verfication https://github.com/googleapis/release-please-action/issues/986

**Comment by meyuviofficial** [comment]
As per out GitHub Org policies, all the non-verfied actions would be disabled by default. Do you have any timeline on the verification process? Because of this, I'm forced to use the CLI in the GitHub workflow.

**Comment by peterhirn** [comment]
@meyuviofficial Just use a pinned action until this is re-verified

```yaml
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4
        id: release
```
